spring:
  datasource:
    embedded-database-connection: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testDb
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database: H2
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: embedded
      platform: h2
      data-locations: classpath:data-h2.sql
